### ISSUE TITLE
Model and build out functionality for insects

### ISSUE THREAD

**Issue by kristiechow** [dali-lab/tarsier#114]

**Comment by yoondoong** [comment]
- [x] floor bug, randomly generates and then make them move
- [x] tree bug, randomly finds spawn points to generate

- [x] fix the flying bug
- [x] constraints around bug movement
- [x] bug falling off the floor
- [x] bug crawling into saplings (create colliders for them)
- [x] also make it crawl on the floor (maybe add some gravity to it so that no matter how the topography is, the bug will crawl on the floor)
- [x] why are some bugs jumping when first spawned?
----> was caused whenever bug spawned on top of an already spawned bug
----> as solution, generateBug script creates a temporary sphere with a random position as the center, checks if the sphere collides with any game object, if did not collide, instantiates the bug prefab!
